# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(scheme: "Chimere")
    upload_to_app_store(skip_binary_upload: true, skip_metadata: true)
  end
end

lane :certificates do
	match(app_identifier: "com.DRojo.chimere")
end

lane :beta do  
	match(app_identifier: "com.DRojo.chimere")
	build_app
  	upload_to_testflight
  	slack(message: "Successfully distributed a new beta build")
end


lane :release do
	sync_code_signing(type: "appstore")
	#capture_screenshots
	#sync_code_signing
  	#build_app
	build_app(scheme: "Chimere")
	#upload_to_app_store
	#slack(message: "Successfully uploaded a new App Store build")   
end

#lane :release do
#cert(development:true)

  	#sigh(development:true,force: true)
	#build_app(scheme: "Chimere") 
 	#sync_code_signing(type: "appstore")  
  	#build_app(scheme: "Chimere")

	#cert
  	#sigh(force: true)
	#capture_screenshots      
  	#sync_code_signing(type: "appstore") 
  	#build_app(scheme: "Chimere")
 	#upload_to_app_store              
  	#slack(message: "Successfully uploaded a new App Store build")
#end
